name: Simulation and build project

on: 
  push:
    tags:
    - 'v*'

env:
    image_name: r0d0s/fpga_tools:latest
    container_name: fpga_tools

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v2
      - name: Run Docker container
        uses: addnab/docker-run-action@v3
        with:
            image: ${{env.image_name}}
            options: --name ${{env.container_name}}
            run: |
              git clone https://github.com/RDSik/axis-uart.git
              cd axis-uart
              make project
      - name: Create artifact
        run: |
          docker cp ${{env.container_name}}:/axis-uart/project/axis_uart_top/impl/pnr/axis_uart_top.fs ./
          tar -cvf bitstream.tar.gz axis_uart_top.fs
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bitstream.tar.gz"
          bodyFile: "release.md"
